# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\ccheney\Dropbox (MIT)\MICA\Creator\libraries\micaComponents_testing\fileGenerators_v1_0.cydsn\fileGenerators_v1_0.cyprj
# Date: Mon, 01 Oct 2018 22:22:04 GMT
#set_units -time ns
create_clock -name {CyRouted1} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyWCO} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/wco}]]
create_clock -name {CyLFClk} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyECO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/eco}]]
create_clock -name {CyIMO} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFClk} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySysClk} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/sysclk}]]


# Component constraints for C:\Users\ccheney\Dropbox (MIT)\MICA\Creator\libraries\micaComponents_testing\fileGenerators_v1_0.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\ccheney\Dropbox (MIT)\MICA\Creator\libraries\micaComponents_testing\fileGenerators_v1_0.cydsn\fileGenerators_v1_0.cyprj
# Date: Mon, 01 Oct 2018 22:22:03 GMT
